In [3]:

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# Locate the project folder
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

# Locate the raw dataset
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "ChargingRecords.csv"

print("Project folder:", PROJECT_ROOT)
print("Dataset path:", DATA_PATH)
print("Dataset exists:", DATA_PATH.exists())

Project folder: c:\Users\Dell\Documents\EV_Charging_Demand_Analysis
Dataset path: c:\Users\Dell\Documents\EV_Charging_Demand_Analysis\data\raw\ChargingRecords.csv
Dataset exists: True

In [4]:

df = pd.read_csv(DATA_PATH)

print("DATA LOADING COMPLETED")
print("Dataset shape:", df.shape)

display(df.head())

DATA LOADING COMPLETED
Dataset shape: (72856, 13)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54,2022-09-15 23:59,185,20.36
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01,2022-09-14 21:31,90,10.19
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54,2022-09-14 19:54,60,6.78
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32,2022-09-30 0:16,344,37.65
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30,2022-09-26 0:30,300,33.81

In [5]:

# Display column names
print("COLUMN NAMES:")
print(df.columns.tolist())

print("\nFIRST 5 ROWS:")
display(df.head())

print("\nDATASET INFORMATION:")
df.info()

print("\nMISSING VALUES:")
display(df.isnull().sum().to_frame(name="Missing Count"))

print("\nDUPLICATE ROWS:")
print("Total duplicate rows:", df.duplicated().sum())

print("\nNUMERICAL SUMMARY:")
display(df.describe().T)

COLUMN NAMES:
['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType', 'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime', 'EndDatetime', 'Duration', 'Demand']

FIRST 5 ROWS:

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54,2022-09-15 23:59,185,20.36
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01,2022-09-14 21:31,90,10.19
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54,2022-09-14 19:54,60,6.78
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32,2022-09-30 0:16,344,37.65
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30,2022-09-26 0:30,300,33.81

DATASET INFORMATION:
<class 'pandas.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  str
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  str
 6   StartTime       72856 non-null  str
 7   EndDay          72856 non-null  str
 8   EndTime         72856 non-null  str
 9   StartDatetime   72856 non-null  str
 10  EndDatetime     72856 non-null  str
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), str(7)
memory usage: 7.2 MB

MISSING VALUES:

                Missing Count
UserID                      0
ChargerID                   0
ChargerCompany              0
Location                    0
ChargerType                 0
StartDay                    0
StartTime                   0
EndDay                      0
EndTime                     0
StartDatetime               0
EndDatetime                 0
Duration                    0
Demand                      0

DUPLICATE ROWS:
Total duplicate rows: 13

NUMERICAL SUMMARY:

                  count        mean         std    min     25%    50%    75%     max
UserID          72856.0  338.164667  553.970996   0.00    0.00   62.0  407.0  2501.0
ChargerID       72856.0  525.489212  569.544469   1.00  107.00  301.0  738.0  2671.0
ChargerCompany  72856.0    0.627443    0.483489   0.00    0.00    1.0    1.0     1.0
ChargerType     72856.0    0.205240    0.403880   0.00    0.00    0.0    0.0     1.0
Duration        72856.0  151.194054  146.430286 -29.00   40.00  112.0  202.0  1573.0
Demand          72856.0   17.444445   13.492728   0.01    7.53   14.1   23.2    97.0

In [6]:

# 1. Investigate duration values
print("DURATION QUALITY CHECK")
print("Negative durations:", (df["Duration"] < 0).sum())
print("Zero durations:", (df["Duration"] == 0).sum())
print("Positive durations:", (df["Duration"] > 0).sum())

# 2. Inspect records with invalid durations
print("\nRECORDS WITH ZERO OR NEGATIVE DURATION")
display(
    df.loc[df["Duration"] <= 0,
           ["UserID", "StartDatetime", "EndDatetime", "Duration", "Demand"]]
      .head(10)
)

# 3. Check duplicate records
print("\nDUPLICATE CHECK")
print("Exact duplicate rows:", df.duplicated().sum())

# 4. Convert datetime columns safely for validation
start_dt = pd.to_datetime(df["StartDatetime"], errors="coerce")
end_dt = pd.to_datetime(df["EndDatetime"], errors="coerce")

print("\nDATETIME VALIDATION")
print("Invalid start datetimes:", start_dt.isna().sum())
print("Invalid end datetimes:", end_dt.isna().sum())
print("End before start:", (end_dt < start_dt).sum())

# 5. Check Demand
print("\nDEMAND VALIDATION")
print("Negative Demand:", (df["Demand"] < 0).sum())
print("Zero Demand:", (df["Demand"] == 0).sum())

DURATION QUALITY CHECK
Negative durations: 17
Zero durations: 718
Positive durations: 72121

RECORDS WITH ZERO OR NEGATIVE DURATION

     UserID     StartDatetime       EndDatetime  Duration  Demand
32        0  2022-06-10 18:52  2022-06-10 18:52         0    0.54
33        0  2022-06-10 19:14  2022-06-10 19:14         0    0.55
50        0  2022-03-01 12:45  2022-03-01 13:34         0    5.58
57        0   2022-03-13 9:49  2022-03-13 10:41         0    4.66
66        0   2022-02-11 8:45  2022-02-11 10:00         0    8.34
106       0  2022-06-09 14:40  2022-06-09 14:40         0    0.02
141       0  2022-08-01 11:14  2022-08-01 11:14         0    0.02
244    1068  2021-12-26 16:34  2021-12-26 17:01         0    3.03
246    1068  2021-12-27 17:29  2021-12-27 20:24         0   17.32
254       0  2022-06-26 14:58  2022-06-26 14:59         0    0.05

DUPLICATE CHECK
Exact duplicate rows: 13

DATETIME VALIDATION
Invalid start datetimes: 0
Invalid end datetimes: 0
End before start: 17

DEMAND VALIDATION
Negative Demand: 0
Zero Demand: 0

In [7]:

# Create a temporary inspection copy
inspection_df = df.copy()

inspection_df["StartDatetime"] = pd.to_datetime(
    inspection_df["StartDatetime"], errors="coerce"
)
inspection_df["EndDatetime"] = pd.to_datetime(
    inspection_df["EndDatetime"], errors="coerce"
)

# Calculate duration from timestamps
inspection_df["CalculatedDuration"] = (
    inspection_df["EndDatetime"] - inspection_df["StartDatetime"]
).dt.total_seconds() / 60

# Find records where end datetime is earlier than start datetime
suspicious_records = inspection_df[
    inspection_df["EndDatetime"] < inspection_df["StartDatetime"]
]

print("Records where end is before start:", len(suspicious_records))

display(
    suspicious_records[
        ["UserID", "StartDay", "StartTime", "EndDay", "EndTime",
         "StartDatetime", "EndDatetime", "Duration", "CalculatedDuration"]
    ]
)

# Compare stored and timestamp-calculated durations
print("\nDURATION COMPARISON")
print("Negative stored durations:", (inspection_df["Duration"] < 0).sum())
print("Zero stored durations:", (inspection_df["Duration"] == 0).sum())
print(
    "Records with duration mismatch:",
    (
        inspection_df["Duration"] - inspection_df["CalculatedDuration"]
    ).abs().gt(1).sum()
)

Records where end is before start: 17

,UserID,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,CalculatedDuration
55422,1403,2022-02-15,15:04:54,2022-02-15,14:35:36,2022-02-15 15:04:00,2022-02-15 14:35:00,-29,-29.0
55425,1403,2022-02-24,14:27:44,2022-02-24,14:18:35,2022-02-24 14:27:00,2022-02-24 14:18:00,-9,-9.0
55427,1403,2022-01-17,14:47:03,2022-01-17,14:39:24,2022-01-17 14:47:00,2022-01-17 14:39:00,-8,-8.0
55455,37,2022-04-29,18:58:46,2022-04-29,18:52:20,2022-04-29 18:58:00,2022-04-29 18:52:00,-6,-6.0
55457,55,2022-05-07,16:24:20,2022-05-07,16:03:03,2022-05-07 16:24:00,2022-05-07 16:03:00,-21,-21.0
55458,74,2022-04-29,15:48:51,2022-04-29,15:43:07,2022-04-29 15:48:00,2022-04-29 15:43:00,-6,-5.0
55459,92,2022-03-27,15:17:53,2022-03-27,15:10:38,2022-03-27 15:17:00,2022-03-27 15:10:00,-7,-7.0
55460,92,2022-02-05,18:52:39,2022-02-05,18:50:15,2022-02-05 18:52:00,2022-02-05 18:50:00,-2,-2.0
55464,266,2022-05-08,12:02:28,2022-05-08,11:42:02,2022-05-08 12:02:00,2022-05-08 11:42:00,-20,-20.0
55465,326,2022-01-09,14:29:15,2022-01-09,14:20:28,2022-01-09 14:29:00,2022-01-09 14:20:00,-9,-9.0
55469,1768,2022-04-07,12:25:32,2022-04-07,12:12:11,2022-04-07 12:25:00,2022-04-07 12:12:00,-13,-13.0
57800,55,2022-04-09,11:29:43,2022-04-09,11:23:46,2022-04-09 11:29:00,2022-04-09 11:23:00,-6,-6.0
57802,1474,2022-05-05,17:48:01,2022-05-05,17:31:39,2022-05-05 17:48:00,2022-05-05 17:31:00,-16,-17.0
57803,1766,2022-04-17,18:59:44,2022-04-17,18:54:21,2022-04-17 18:59:00,2022-04-17 18:54:00,-5,-5.0
63503,1575,2022-03-19,15:32:26,2022-03-19,15:24:33,2022-03-19 15:32:00,2022-03-19 15:24:00,-8,-8.0
63504,1575,2022-03-22,17:19:11,2022-03-22,16:55:39,2022-03-22 17:19:00,2022-03-22 16:55:00,-24,-24.0
65029,140,2022-03-30,13:20:34,2022-03-30,13:04:57,2022-03-30 13:20:00,2022-03-30 13:04:00,-16,-16.0

DURATION COMPARISON
Negative stored durations: 17
Zero stored durations: 718
Records with duration mismatch: 3497

In [8]:

# Create a temporary copy for investigation
check_df = df.copy()

check_df["StartDatetime"] = pd.to_datetime(
    check_df["StartDatetime"], errors="coerce"
)
check_df["EndDatetime"] = pd.to_datetime(
    check_df["EndDatetime"], errors="coerce"
)

# Calculate elapsed minutes from the available timestamps
check_df["CalculatedDuration"] = (
    check_df["EndDatetime"] - check_df["StartDatetime"]
).dt.total_seconds() / 60

check_df["DurationDifference"] = (
    check_df["Duration"] - check_df["CalculatedDuration"]
)

# Summary of differences
print("DURATION DIFFERENCE SUMMARY")
display(check_df["DurationDifference"].describe())

# Show 10 records with the largest absolute differences
print("\nLARGEST DURATION DIFFERENCES")
display(
    check_df.loc[
        check_df["DurationDifference"].abs().nlargest(10).index,
        [
            "StartDay", "StartTime", "EndDay", "EndTime",
            "Duration", "CalculatedDuration", "DurationDifference"
        ]
    ]
)

# Compare the separate date/time fields with combined datetime columns
print("\nZERO-DURATION EXAMPLES")
display(
    check_df.loc[
        check_df["Duration"] == 0,
        [
            "StartDay", "StartTime", "EndDay", "EndTime",
            "StartDatetime", "EndDatetime", "Duration", "Demand"
        ]
    ].head(10)
)

DURATION DIFFERENCE SUMMARY

count    72856.000000
mean        -4.311203
std         60.608690
min      -4320.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        870.000000
Name: DurationDifference, dtype: float64

LARGEST DURATION DIFFERENCES

         StartDay StartTime      EndDay   EndTime  Duration  CalculatedDuration  DurationDifference
68973  2022-05-14  13:59:33  2022-05-17  20:36:35       397              4717.0             -4320.0
18795  2021-10-01  18:31:08  2021-10-04  13:17:25       101              4006.0             -3905.0
13420  2022-03-30  22:04:34  2022-04-02  15:00:15       157              3896.0             -3739.0
8022   2022-03-05   9:09:11  2022-03-07  12:09:13       132              3060.0             -2928.0
72198  2021-10-25   8:57:16  2021-10-27   9:00:02         3              2883.0             -2880.0
72429  2022-03-24  22:08:20  2022-03-27  13:01:11       893              3773.0             -2880.0
4911   2021-10-23  23:54:59  2021-10-25  23:50:59       167              2876.0             -2709.0
21530  2022-01-21  23:14:22  2022-01-23  22:28:59       214              2834.0             -2620.0
21540  2021-11-13  23:05:57  2021-11-15  20:08:43       177              2703.0             -2526.0
4862   2022-03-08  18:24:41  2022-03-10  12:49:59       229              2545.0             -2316.0

ZERO-DURATION EXAMPLES

       StartDay StartTime      EndDay   EndTime       StartDatetime         EndDatetime  Duration  Demand
32   2022-06-10  18:52:53  2022-06-10  18:52:53 2022-06-10 18:52:00 2022-06-10 18:52:00         0    0.54
33   2022-06-10  19:14:26  2022-06-10  19:14:26 2022-06-10 19:14:00 2022-06-10 19:14:00         0    0.55
50   2022-03-01  12:45:35  2022-03-01  13:34:38 2022-03-01 12:45:00 2022-03-01 13:34:00         0    5.58
57   2022-03-13   9:49:06  2022-03-13  10:41:42 2022-03-13 09:49:00 2022-03-13 10:41:00         0    4.66
66   2022-02-11   8:45:14  2022-02-11  10:00:14 2022-02-11 08:45:00 2022-02-11 10:00:00         0    8.34
106  2022-06-09  14:40:16  2022-06-09  14:40:39 2022-06-09 14:40:00 2022-06-09 14:40:00         0    0.02
141  2022-08-01  11:14:23  2022-08-01  11:14:42 2022-08-01 11:14:00 2022-08-01 11:14:00         0    0.02
244  2021-12-26  16:34:37  2021-12-26  17:01:55 2021-12-26 16:34:00 2021-12-26 17:01:00         0    3.03
246  2021-12-27  17:29:49  2021-12-27  20:24:22 2021-12-27 17:29:00 2021-12-27 20:24:00         0   17.32
254  2022-06-26  14:58:45  2022-06-26  14:59:14 2022-06-26 14:58:00 2022-06-26 14:59:00         0    0.05

In [9]:

# Work on a separate copy; keep the original df unchanged
time_check = df.copy()

# Reconstruct full timestamps using the date and time fields
time_check["StartFull"] = pd.to_datetime(
    time_check["StartDay"].astype(str) + " " +
    time_check["StartTime"].astype(str),
    errors="coerce"
)

time_check["EndFull"] = pd.to_datetime(
    time_check["EndDay"].astype(str) + " " +
    time_check["EndTime"].astype(str),
    errors="coerce"
)

# Calculate duration using the full timestamps
time_check["DurationFromFullTime"] = (
    time_check["EndFull"] - time_check["StartFull"]
).dt.total_seconds() / 60

# Compare stored duration with reconstructed duration
time_check["DurationDifferenceFull"] = (
    time_check["Duration"] - time_check["DurationFromFullTime"]
)

print("Invalid reconstructed start times:",
      time_check["StartFull"].isna().sum())
print("Invalid reconstructed end times:",
      time_check["EndFull"].isna().sum())
print("End before start:",
      (time_check["EndFull"] < time_check["StartFull"]).sum())
print("Negative stored durations:",
      (time_check["Duration"] < 0).sum())
print("Zero stored durations:",
      (time_check["Duration"] == 0).sum())
print("Duration mismatches over 1 minute:",
      time_check["DurationDifferenceFull"].abs().gt(1).sum())

print("\nLARGEST REMAINING MISMATCHES")
display(
    time_check.loc[
        time_check["DurationDifferenceFull"].abs().nlargest(10).index,
        [
            "StartDay", "StartTime", "EndDay", "EndTime",
            "Duration", "DurationFromFullTime",
            "DurationDifferenceFull"
        ]
    ]
)

Invalid reconstructed start times: 0
Invalid reconstructed end times: 0
End before start: 17
Negative stored durations: 17
Zero stored durations: 718
Duration mismatches over 1 minute: 4263

LARGEST REMAINING MISMATCHES

         StartDay StartTime      EndDay   EndTime  Duration  DurationFromFullTime  DurationDifferenceFull
68973  2022-05-14  13:59:33  2022-05-17  20:36:35       397           4717.033333            -4320.033333
18795  2021-10-01  18:31:08  2021-10-04  13:17:25       101           4006.283333            -3905.283333
13420  2022-03-30  22:04:34  2022-04-02  15:00:15       157           3895.683333            -3738.683333
8022   2022-03-05   9:09:11  2022-03-07  12:09:13       132           3060.033333            -2928.033333
72429  2022-03-24  22:08:20  2022-03-27  13:01:11       893           3772.850000            -2879.850000
72198  2021-10-25   8:57:16  2021-10-27   9:00:02         3           2882.766667            -2879.766667
4911   2021-10-23  23:54:59  2021-10-25  23:50:59       167           2876.000000            -2709.000000
21530  2022-01-21  23:14:22  2022-01-23  22:28:59       214           2834.616667            -2620.616667
21540  2021-11-13  23:05:57  2021-11-15  20:08:43       177           2702.766667            -2525.766667
4862   2022-03-08  18:24:41  2022-03-10  12:49:59       229           2545.300000            -2316.300000

In [10]:

# Summarize the relationship between stored and calculated durations
valid_time = time_check[
    time_check["DurationFromFullTime"].notna()
].copy()

valid_time["AbsoluteDifference"] = (
    valid_time["Duration"] - valid_time["DurationFromFullTime"]
).abs()

print("TOTAL RECORDS:", len(valid_time))
print(
    "Exact matches (within 1 minute):",
    (valid_time["AbsoluteDifference"] <= 1).sum()
)
print(
    "Differences greater than 1 minute:",
    (valid_time["AbsoluteDifference"] > 1).sum()
)

# Compare stored duration with timestamp-based duration
print("\nCORRELATION BETWEEN DURATIONS:")
display(
    valid_time[["Duration", "DurationFromFullTime"]].corr()
)

# Inspect records with the largest duration differences
print("\nLARGEST MISMATCHES — INCLUDING DEMAND:")
display(
    valid_time.loc[
        valid_time["AbsoluteDifference"].nlargest(10).index,
        [
            "UserID", "ChargerID", "Location", "ChargerType",
            "StartFull", "EndFull", "Duration",
            "DurationFromFullTime", "Demand"
        ]
    ]
)

TOTAL RECORDS: 72856
Exact matches (within 1 minute): 68593
Differences greater than 1 minute: 4263

CORRELATION BETWEEN DURATIONS:

                      Duration  DurationFromFullTime
Duration               1.00000               0.92468
DurationFromFullTime   0.92468               1.00000

LARGEST MISMATCHES — INCLUDING DEMAND:

,UserID,ChargerID,Location,ChargerType,StartFull,EndFull,Duration,DurationFromFullTime,Demand
68973,285,1784,apartment,0,2022-05-14 13:59:33,2022-05-17 20:36:35,397,4717.033333,22.93
18795,0,114,apartment,0,2021-10-01 18:31:08,2021-10-04 13:17:25,101,4006.283333,2.30
13420,0,69,apartment,0,2022-03-30 22:04:34,2022-04-02 15:00:15,157,3895.683333,16.70
8022,0,33,apartment,0,2022-03-05 09:09:11,2022-03-07 12:09:13,132,3060.033333,14.40
72429,1860,2499,public institution,0,2022-03-24 22:08:20,2022-03-27 13:01:11,893,3772.850000,23.03
72198,1093,2414,apartment,1,2021-10-25 08:57:16,2021-10-27 09:00:02,3,2882.766667,15.32
4911,0,21,apartment,0,2021-10-23 23:54:59,2021-10-25 23:50:59,167,2876.000000,5.10
21530,0,140,apartment,0,2022-01-21 23:14:22,2022-01-23 22:28:59,214,2834.616667,7.20
21540,0,140,apartment,0,2021-11-13 23:05:57,2021-11-15 20:08:43,177,2702.766667,5.40
4862,0,21,apartment,0,2022-03-08 18:24:41,2022-03-10 12:49:59,229,2545.300000,8.00

In [11]:

# Flag records with duration mismatches
time_check["DurationMismatch"] = (
    time_check["DurationDifferenceFull"].abs() > 1
)

time_check["InvalidDuration"] = time_check["Duration"] < 0
time_check["ZeroDuration"] = time_check["Duration"] == 0

print("DURATION QUALITY BY LOCATION")
display(
    time_check.groupby("Location").agg(
        TotalRecords=("Duration", "size"),
        Mismatches=("DurationMismatch", "sum"),
        NegativeDurations=("InvalidDuration", "sum"),
        ZeroDurations=("ZeroDuration", "sum")
    ).sort_values("Mismatches", ascending=False)
)

print("\nDURATION QUALITY BY CHARGER TYPE")
display(
    time_check.groupby("ChargerType").agg(
        TotalRecords=("Duration", "size"),
        Mismatches=("DurationMismatch", "sum"),
        NegativeDurations=("InvalidDuration", "sum"),
        ZeroDurations=("ZeroDuration", "sum")
    )
)

print("\nDURATION DISTRIBUTION")
display(time_check["Duration"].describe())

DURATION QUALITY BY LOCATION

                    TotalRecords  Mismatches  NegativeDurations  ZeroDurations
Location
hotel                       8600         995                  0            143
apartment                  14038         840                  0            123
company                     7558         706                  0             30
public area                14082         689                  0            124
resort                      8854         494                  0            137
restaurant                  2222         266                  0              6
public institution          7023         169                  0             62
golf                        1029          70                  0              3
market                      3005          20                 17             30
accommodation                187          11                  0              2
camping                     1630           2                  0             10
sightseeing                 1203           1                  0             18
bus garage                    29           0                  0              0
public parking lot          3396           0                  0             30

DURATION QUALITY BY CHARGER TYPE

             TotalRecords  Mismatches  NegativeDurations  ZeroDurations
ChargerType
0                   57903        4262                  0            498
1                   14953           1                 17            220

DURATION DISTRIBUTION

count    72856.000000
mean       151.194054
std        146.430286
min        -29.000000
25%         40.000000
50%        112.000000
75%        202.000000
max       1573.000000
Name: Duration, dtype: float64

In [12]:

# Inspect all records with negative stored durations
negative_records = time_check.loc[
    time_check["Duration"] < 0,
    [
        "UserID", "ChargerID", "ChargerCompany",
        "Location", "ChargerType",
        "StartFull", "EndFull",
        "Duration", "DurationFromFullTime", "Demand"
    ]
].sort_values("Location")

print("Negative duration records:", len(negative_records))
display(negative_records)

# Summarize negative durations by location and charger type
print("\nNEGATIVE DURATIONS BY LOCATION AND CHARGER TYPE")
display(
    time_check.loc[time_check["Duration"] < 0]
    .groupby(["Location", "ChargerType"])
    .agg(
        RecordCount=("Duration", "size"),
        AverageDuration=("Duration", "mean"),
        AverageDemand=("Demand", "mean")
    )
)

Negative duration records: 17

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartFull,EndFull,Duration,DurationFromFullTime,Demand
55422,1403,775,0,market,1,2022-02-15 15:04:54,2022-02-15 14:35:36,-29,-29.300000,11.68
63503,1575,1229,0,market,1,2022-03-19 15:32:26,2022-03-19 15:24:33,-8,-7.883333,37.97
57803,1766,922,0,market,1,2022-04-17 18:59:44,2022-04-17 18:54:21,-5,-5.383333,15.04
57802,1474,922,0,market,1,2022-05-05 17:48:01,2022-05-05 17:31:39,-16,-16.366667,51.99
57800,55,922,0,market,1,2022-04-09 11:29:43,2022-04-09 11:23:46,-6,-5.950000,41.08
55469,1768,778,0,market,1,2022-04-07 12:25:32,2022-04-07 12:12:11,-13,-13.350000,53.24
55465,326,778,0,market,1,2022-01-09 14:29:15,2022-01-09 14:20:28,-9,-8.783333,31.68
63504,1575,1229,0,market,1,2022-03-22 17:19:11,2022-03-22 16:55:39,-24,-23.533333,25.49
55464,266,778,0,market,1,2022-05-08 12:02:28,2022-05-08 11:42:02,-20,-20.433333,3.28
55459,92,778,0,market,1,2022-03-27 15:17:53,2022-03-27 15:10:38,-7,-7.250000,20.99
55458,74,778,0,market,1,2022-04-29 15:48:51,2022-04-29 15:43:07,-6,-5.733333,19.36
55457,55,778,0,market,1,2022-05-07 16:24:20,2022-05-07 16:03:03,-21,-21.283333,13.39
55455,37,778,0,market,1,2022-04-29 18:58:46,2022-04-29 18:52:20,-6,-6.433333,31.90
55427,1403,775,0,market,1,2022-01-17 14:47:03,2022-01-17 14:39:24,-8,-7.650000,17.77
55425,1403,775,0,market,1,2022-02-24 14:27:44,2022-02-24 14:18:35,-9,-9.150000,34.56
55460,92,778,0,market,1,2022-02-05 18:52:39,2022-02-05 18:50:15,-2,-2.400000,31.59
65029,140,1347,0,market,1,2022-03-30 13:20:34,2022-03-30 13:04:57,-16,-15.616667,23.10

NEGATIVE DURATIONS BY LOCATION AND CHARGER TYPE

                      RecordCount  AverageDuration  AverageDemand
Location ChargerType
market   1                     17       -12.058824      27.300588

In [13]:

# Preserve the original dataset and create a working copy
df_clean = df.copy()

initial_rows = len(df_clean)

# 1. Remove exact duplicate rows
duplicate_count = int(df_clean.duplicated().sum())
df_clean = df_clean.drop_duplicates().copy()

# 2. Parse date and time columns
df_clean["StartDay"] = pd.to_datetime(
    df_clean["StartDay"], errors="coerce"
)
df_clean["EndDay"] = pd.to_datetime(
    df_clean["EndDay"], errors="coerce"
)

df_clean["StartDatetime"] = pd.to_datetime(
    df_clean["StartDay"].dt.strftime("%Y-%m-%d") + " " +
    df_clean["StartTime"].astype(str),
    errors="coerce"
)

df_clean["EndDatetime"] = pd.to_datetime(
    df_clean["EndDay"].dt.strftime("%Y-%m-%d") + " " +
    df_clean["EndTime"].astype(str),
    errors="coerce"
)

# 3. Remove records with invalid timestamps
invalid_datetime_mask = (
    df_clean["StartDatetime"].isna()
    | df_clean["EndDatetime"].isna()
)
invalid_datetime_count = int(invalid_datetime_mask.sum())
df_clean = df_clean.loc[~invalid_datetime_mask].copy()

# 4. Remove negative stored durations from the main cleaned dataset
negative_duration_count = int((df_clean["Duration"] < 0).sum())
df_clean = df_clean.loc[df_clean["Duration"] >= 0].copy()

# 5. Create useful time-based features
df_clean["StartHour"] = df_clean["StartDatetime"].dt.hour
df_clean["StartMonth"] = df_clean["StartDatetime"].dt.month
df_clean["StartWeekday"] = df_clean["StartDatetime"].dt.day_name()
df_clean["StartDate"] = df_clean["StartDatetime"].dt.date

# 6. Report cleaning results
print("INITIAL ROWS:", initial_rows)
print("DUPLICATES REMOVED:", duplicate_count)
print("INVALID DATETIME ROWS REMOVED:", invalid_datetime_count)
print("NEGATIVE DURATION ROWS REMOVED:", negative_duration_count)
print("FINAL ROWS:", len(df_clean))
print("ZERO-DURATION ROWS RETAINED:", (df_clean["Duration"] == 0).sum())
print("MISSING VALUES AFTER CLEANING:", int(df_clean.isna().sum().sum()))

display(df_clean.head())

INITIAL ROWS: 72856
DUPLICATES REMOVED: 13
INVALID DATETIME ROWS REMOVED: 0
NEGATIVE DURATION ROWS REMOVED: 17
FINAL ROWS: 72826
ZERO-DURATION ROWS RETAINED: 718
MISSING VALUES AFTER CLEANING: 0

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartHour,StartMonth,StartWeekday,StartDate
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54:02,2022-09-15 23:59:13,185,20.36,20,9,Thursday,2022-09-15
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01:05,2022-09-14 21:31:04,90,10.19,20,9,Wednesday,2022-09-14
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54:30,2022-09-14 19:54:29,60,6.78,18,9,Wednesday,2022-09-14
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32:51,2022-09-30 00:16:42,344,37.65,18,9,Thursday,2022-09-29
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30:15,2022-09-26 00:30:14,300,33.81,19,9,Sunday,2022-09-25

In [14]:

# Create the processed data folder
PROCESSED_PATH = PROJECT_ROOT / "data" / "processed"
PROCESSED_PATH.mkdir(parents=True, exist_ok=True)

# Save the cleaned dataset
cleaned_file = PROCESSED_PATH / "ChargingRecords_Cleaned.csv"
df_clean.to_csv(cleaned_file, index=False)

print("CLEANING PIPELINE COMPLETED SUCCESSFULLY")
print("Saved file:", cleaned_file)
print("Final dataset shape:", df_clean.shape)

CLEANING PIPELINE COMPLETED SUCCESSFULLY
Saved file: c:\Users\Dell\Documents\EV_Charging_Demand_Analysis\data\processed\ChargingRecords_Cleaned.csv
Final dataset shape: (72826, 17)

In [15]:

# Calculate session duration from timestamps (in minutes)
df_clean["DurationFromTimestamps"] = (
    df_clean["EndDatetime"] - df_clean["StartDatetime"]
).dt.total_seconds() / 60

# Compare stored and calculated duration
df_clean["DurationDifference"] = (
    df_clean["Duration"] - df_clean["DurationFromTimestamps"]
)

mismatch_mask = df_clean["DurationDifference"].abs() > 1

print("Total cleaned records:", len(df_clean))
print("Duration mismatches (> 1 minute):", int(mismatch_mask.sum()))
print("Records matching within 1 minute:", int((~mismatch_mask).sum()))

display(
    df_clean.loc[
        mismatch_mask,
        [
            "Location",
            "StartDatetime",
            "EndDatetime",
            "Duration",
            "DurationFromTimestamps",
            "DurationDifference",
        ],
    ].head(10)
)

Total cleaned records: 72826
Duration mismatches (> 1 minute): 4263
Records matching within 1 minute: 68563

    Location       StartDatetime         EndDatetime  Duration  DurationFromTimestamps  DurationDifference
15     hotel 2022-08-19 17:10:57 2022-08-19 19:10:57         4              120.000000         -116.000000
50     hotel 2022-03-01 12:45:35 2022-03-01 13:34:38         0               49.050000          -49.050000
57     hotel 2022-03-13 09:49:06 2022-03-13 10:41:42         0               52.600000          -52.600000
66     hotel 2022-02-11 08:45:14 2022-02-11 10:00:14         0               75.000000          -75.000000
244    hotel 2021-12-26 16:34:37 2021-12-26 17:01:55         0               27.300000          -27.300000
246    hotel 2021-12-27 17:29:49 2021-12-27 20:24:22         0              174.550000         -174.550000
348    hotel 2022-03-31 22:46:37 2022-04-01 02:39:42         0              233.083333         -233.083333
349    hotel 2022-04-14 21:17:15 2022-04-15 00:29:33         0              192.300000         -192.300000
361    hotel 2022-03-27 08:11:32 2022-03-27 09:27:46         0               76.233333          -76.233333
364    hotel 2022-03-22 10:05:35 2022-03-22 16:19:48         0              374.216667         -374.216667

In [16]:

# Summarize duration mismatches by location
mismatch_summary = (
    df_clean.assign(DurationMismatch=mismatch_mask)
    .groupby("Location")
    .agg(
        TotalRecords=("DurationMismatch", "size"),
        MismatchRecords=("DurationMismatch", "sum"),
    )
    .reset_index()
)

mismatch_summary["MismatchPercentage"] = (
    mismatch_summary["MismatchRecords"]
    / mismatch_summary["TotalRecords"] * 100
).round(2)

mismatch_summary = mismatch_summary.sort_values(
    "MismatchRecords", ascending=False
)

display(mismatch_summary)

# Inspect the 10 largest duration discrepancies
largest_mismatches = df_clean.loc[
    mismatch_mask,
    [
        "Location",
        "ChargerType",
        "StartDatetime",
        "EndDatetime",
        "Duration",
        "DurationFromTimestamps",
        "DurationDifference",
    ],
].copy()

largest_mismatches["AbsoluteDifference"] = (
    largest_mismatches["DurationDifference"].abs()
)

display(
    largest_mismatches.sort_values(
        "AbsoluteDifference", ascending=False
    ).head(10)
)

              Location  TotalRecords  MismatchRecords  MismatchPercentage
6                hotel          8598              995               11.57
1            apartment         14036              840                5.98
4              company          7557              706                9.34
8          public area         14076              689                4.89
11              resort          8854              494                5.58
12          restaurant          2222              266               11.97
9   public institution          7023              169                2.41
5                 golf          1029               70                6.80
7               market          2988               20                0.67
0        accommodation           187               11                5.88
3              camping          1630                2                0.12
13         sightseeing          1203                1                0.08
2           bus garage            29                0                0.00
10  public parking lot          3394                0                0.00

,Location,ChargerType,StartDatetime,EndDatetime,Duration,DurationFromTimestamps,DurationDifference,AbsoluteDifference
68973,apartment,0,2022-05-14 13:59:33,2022-05-17 20:36:35,397,4717.033333,-4320.033333,4320.033333
18795,apartment,0,2021-10-01 18:31:08,2021-10-04 13:17:25,101,4006.283333,-3905.283333,3905.283333
13420,apartment,0,2022-03-30 22:04:34,2022-04-02 15:00:15,157,3895.683333,-3738.683333,3738.683333
8022,apartment,0,2022-03-05 09:09:11,2022-03-07 12:09:13,132,3060.033333,-2928.033333,2928.033333
72429,public institution,0,2022-03-24 22:08:20,2022-03-27 13:01:11,893,3772.850000,-2879.850000,2879.850000
72198,apartment,1,2021-10-25 08:57:16,2021-10-27 09:00:02,3,2882.766667,-2879.766667,2879.766667
4911,apartment,0,2021-10-23 23:54:59,2021-10-25 23:50:59,167,2876.000000,-2709.000000,2709.000000
21530,apartment,0,2022-01-21 23:14:22,2022-01-23 22:28:59,214,2834.616667,-2620.616667,2620.616667
21540,apartment,0,2021-11-13 23:05:57,2021-11-15 20:08:43,177,2702.766667,-2525.766667,2525.766667
4862,apartment,0,2022-03-08 18:24:41,2022-03-10 12:49:59,229,2545.300000,-2316.300000,2316.300000

In [17]:

# Classify mismatches by their absolute size, in minutes
abs_diff = df_clean["DurationDifference"].abs()

severity_summary = pd.Series({
    "Mismatch > 1 minute": (abs_diff > 1).sum(),
    "Mismatch > 30 minutes": (abs_diff > 30).sum(),
    "Mismatch > 60 minutes": (abs_diff > 60).sum(),
    "Mismatch > 6 hours": (abs_diff > 360).sum(),
    "Mismatch > 24 hours": (abs_diff > 1440).sum(),
})

display(severity_summary.to_frame(name="RecordCount"))

# Check whether the stored duration or timestamp duration is larger
print(
    "Stored duration is shorter:",
    int((df_clean.loc[mismatch_mask, "DurationDifference"] < -1).sum())
)

print(
    "Stored duration is longer:",
    int((df_clean.loc[mismatch_mask, "DurationDifference"] > 1).sum())
)

                       RecordCount
Mismatch > 1 minute           4263
Mismatch > 30 minutes         1623
Mismatch > 60 minutes          614
Mismatch > 6 hours             317
Mismatch > 24 hours             15

Stored duration is shorter: 4184
Stored duration is longer: 79

In [18]:

# Flag records with duration inconsistencies
df_clean["DurationMismatch"] = (
    df_clean["DurationDifference"].abs() > 1
).astype(int)

# Categorize mismatch severity
df_clean["DurationQuality"] = np.select(
    [
        df_clean["DurationDifference"].abs() <= 1,
        df_clean["DurationDifference"].abs() <= 30,
        df_clean["DurationDifference"].abs() <= 60,
        df_clean["DurationDifference"].abs() <= 360,
    ],
    [
        "Match",
        "Minor mismatch",
        "Moderate mismatch",
        "Major mismatch",
    ],
    default="Severe mismatch",
)

# Summarize the quality flags
print("Duration quality summary:")
display(
    df_clean["DurationQuality"]
    .value_counts()
    .rename_axis("DurationQuality")
    .to_frame("RecordCount")
)

print("Total records:", len(df_clean))
print("Missing values:", int(df_clean.isna().sum().sum()))

Duration quality summary:

                   RecordCount
DurationQuality
Match                    68563
Minor mismatch            2640
Moderate mismatch         1009
Severe mismatch            317
Major mismatch             297

Total records: 72826
Missing values: 0

In [19]:

cleaned_file = PROCESSED_PATH / "ChargingRecords_Cleaned.csv"
df_clean.to_csv(cleaned_file, index=False)

print("UPDATED CLEANED DATASET SAVED")
print("File:", cleaned_file)
print("Shape:", df_clean.shape)

UPDATED CLEANED DATASET SAVED
File: c:\Users\Dell\Documents\EV_Charging_Demand_Analysis\data\processed\ChargingRecords_Cleaned.csv
Shape: (72826, 21)